### ISSUE TITLE
Ошибки в PostgreSQL < 9.6

### ISSUE THREAD

**Issue by allknower** [levinsv/pgadmin3#11]
Добрый день.
На PostgreSQL 9.3 (PostgreSQL 9.3.19, compiled by Visual C++ build 1600, 64-bit) при подключении к серверу или разворачиванию БД падает ошибка:
`
12:34:03 PM: Error: ERROR:  function to_regproc(unknown) does not exist
LINE 1: select to_regproc('pgpro_edition')::text
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
`

На PostgreSQL 9.5 (PostgreSQL 9.5.12, compiled by Visual C++ build 1800, 64-bit)
При разворачивании схемы или списка функций падает ошибка:
`
12:35:26 PM: Error: ERROR:  column pr.proparallel does not exist
LINE 4: , CASE WHEN pr.proparallel = 'r' THEN 'RESTRICTED'       WHE...
                    ^
`

**Comment by levinsv** [comment]
Добрый день!
Совместимость со старыми версиями не гарантируется. Работа приложения проверяется на 10-ой версии и выше.
Используйте оригинальную версию pgadmin3
