### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by josesydor** [levinsv/pgadmin3#12]
Hello there!
I'd like to ask for two features that would make my life easier:
* ability to change color of database instances icons (they are always beige).
* ability to configure the output pane shortcut (it's crtl + alt + o) and when toggling the output pane on/off it would return to the previous  position on the screen and not the default one.

Thanks!!!

**Comment by levinsv** [comment]
Это может быть полезным.
Я сделал оба предложения.

**Comment by josesydor** [comment]
I guess the quickest way to describe what I wanted is:
Each most recent outputs pane position _is_ the new default position...
