### ISSUE TITLE
корректное скриптование include полей в индексах

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#13]
Спасибо за вашу работу над проектом!

Прошу добавить поддержку в скриптовании индексов INCLUDE полей
Сейчас они просто выводятся в части общего индексного выражения, что неверно.
В настоящее время ( 13-я версия) эту возможность поддерживают только методы доступа индексов B-дерево и GiST.

**Comment by levinsv** [comment]
Добавил вывод include колонок

**Comment by sgrinko** [comment]
Спасибо большое!
