### ISSUE TITLE
Масштабируемость интерфейса 

### ISSUE THREAD

**Issue by Falseclock** [levinsv/pgadmin3#16]
Здравствуйте.

Спасибо что поддерживаете продукт.

Попробовал, но есть много моментов с проблемой масштабируемости

![image](https://user-images.githubusercontent.com/3299139/116686103-280cfc80-a9d5-11eb-9632-bf27eb7caf5d.png)

**Comment by Falseclock** [comment]
текущие настройки

![image](https://user-images.githubusercontent.com/3299139/116686814-2d1e7b80-a9d6-11eb-8435-a94b0336a4ba.png)

**Comment by Falseclock** [comment]
Первый раз в жизни комплил c++ приложение... Да и вообще открыл Visual Studio. Одня компиляция openssql и wxWidgest мозг сожрало....
весь день сидел изучал как компилировать, в итоге добился чтобы и компилировалось и чтобы шрифты и размеры были нужными. 

```xml
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
	<asmv3:application>
		<asmv3:windowsSettings>
			<dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
			<!-- fallback for Windows 7 and 8 -->
			<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
			<!-- adding v1 as fallback would result in v2 not being applied to dialogs on capable systems -->
			<gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>
			<!-- enables GDI DPI scaling -->
		</asmv3:windowsSettings>
	</asmv3:application>
</assembly>
```
Единственное, в SQL pane шрифт пока кривой, ну и иконки фиговые, что в принципе не страшно. В остальном вроде норм. Надо бы еще шрифты добить и будет отлично

![image](https://user-images.githubusercontent.com/3299139/116806054-4fd2a080-ab4c-11eb-9be5-2b90b95ba978.png)

**Comment by Falseclock** [comment]
так.. с  SQL pane вроде разобрался... там нужно менять исходники scintilla в wxWidgets, текущие имеют версию 3.21
в wxWidgets-3.1.5 там уже используется scintilla-3.7.2, а судя по [чейнджлогу ](https://www.scintilla.org/ScintillaHistory.html) нормальный скейлинг шрифтов появился с версии 3.6.

**Comment by levinsv** [comment]
Я не являюсь специалистом ни в wxWidgets ни в C++.
И при попытки сборки сборки с wxWidgets 3.1 у меня при запуске возникало множество ошибок связанных с *.xrc файлами (это описание диалогов в wxWidgets).
Что то поменялась видимо в 3.1. Поэтому я собрал с 3.0 версией где таких ошибок было меньше и я их вручную устранил.
Переход на последние версии wxWidgets возможет только если там ну очень важные изменния будут.

**Comment by Falseclock** [comment]
@levinsv да я тоже не особо спец ))) перкомпилил с wxWidgets 3.1, та же фигня. Это проблема по ходу с wxWidgets

https://stackoverflow.com/questions/67364128/font-quality-scaling-dpi-in-wxstyledtextctrl-wxwidgets

Если я доберусь до истины и скомпилю нормальный wxWidgets без ошибок и чтобы SQL панель была с правильными рендерингом шрифтов, заберете к себе в билд?

**Comment by levinsv** [comment]
Попробую.
