### ISSUE TITLE
Windows build info

### ISSUE THREAD

**Issue by forrest79** [levinsv/pgadmin3#2]
Hi, first of all I want to thank you for this fork and updates. I really hate new pgAdmin 4 and I need to use actual PostgreSQL version, so I'm vary grateful for your Windows binaries. I want to ask you, if it's possible to add some info about how to build pgAdmin III in Windows. I was trying do this for two days with official INSTALL documentation, but I failed. Thanks.

**Comment by levinsv** [comment]
**Hi, my compile options** (from pgadmin3.vcxproj)
      
`<AdditionalIncludeDirectories>$(WXWIN)/lib/vc_dll/mswud/;$(wxwin)/include/msvc;$(wxwin)/include;$(OPENSSL)/include;$(WXWIN)/contrib/include;$(PGDIR)/include;$(PGBUILD)/include/;$(PGBUILD)/libxml2/include/;$(PGBUILD)/libxslt/include/;$(PGBUILD)/iconv/include/;$(PROJECTDIR)/include;$(PGDIR)/include/server;$(PROJECTDIR)/include/libssh2;$(PROJECTDIR)/include/libssh2/Win32;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_CRT_SECURE_NO_DEPRECATE=1;HAVE_OPENSSL_CRYPTO;LIBSSH2_OPENSSL;NDEBUG;WIN32;_WINDOWS;__WINDOWS__;__WIN95__;__WIN32__;WINVER=0x0400;STRICT;__WXMSW__;WXUSINGDLL;wxUSE_UNICODE=1;wxMSVC_VERSION_AUTO;UNICODE;EMBED_XRC;PG_SSL;HAVE_CONNINFO_PARSE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalDependencies>libeay32MD.lib;libpq.lib;libxml2.lib;libxslt.lib;iconv.lib;comctl32.lib;rpcrt4.lib;wsock32.lib;winmm.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>$(OPENSSL)/lib;$(wxwin)/lib/vc110_dll;$(PGDIR)/lib;$(PGBUILD)/lib;$(PGBUILD)/libxml2/lib;$(PGBUILD)/libxslt/lib;$(PGBUILD)/iconv/lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
`

**Comment by forrest79** [comment]
Thanks 👍
