### ISSUE TITLE
Поддержка 14-й версии

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#21]
Можно ли сделать поддержку 14-й версии?

**Comment by levinsv** [comment]
Она есть, хотя 100% поддержку не гарантирую.

**Comment by sgrinko** [comment]
Сейчас при подключении выскакивает окошко о несовместимости....мешает :)
Можно его убрать ?

**Comment by sgrinko** [comment]
Спасибо большое!
