### ISSUE TITLE
Невозможно вставить из буфера обмена в новом окне

### ISSUE THREAD

**Issue by QuickJoey** [levinsv/pgadmin3#22]
Если скопировать текст где-то за пределами открытой вкладки, то пункты главном меню Edit остаются неактивными. Горячими кнопками тоже вставить не получается. Только из контекстного меню.

Скриншот главного меню:
<img width="499" alt="Снимок экрана 2022-02-21 в 14 09 13" src="https://user-images.githubusercontent.com/12407379/154944211-12bc24a8-1ffb-4f63-9fa2-84c7e2d924c4.png">

В этом же состоянии скриншот контекстного меню:
<img width="472" alt="Снимок экрана 2022-02-21 в 14 09 25" src="https://user-images.githubusercontent.com/12407379/154944319-aa89aee1-533e-4f99-bc39-f0f94c12c02e.png">

**Comment by levinsv** [comment]
Исправил в этом commit  [fix issue#22](https://github.com/levinsv/pgadmin3/commit/4c48f7430dfb0acee38ae015275e82c66642c2b8)
