### ISSUE TITLE
Bug in PG10

### ISSUE THREAD

**Issue by YanuszDupa** [levinsv/pgadmin3#24]
in schema/pgindex.cpp line 204-206 is wrong , indnkeyatts property first arrive in PG 11.x , not PG 10.x

```
if (GetConnection()->BackendMinimumVersion(10, 0))
 query += ","+ NumToStr(i)+" <= i.indnkeyatts AS is_key\n"; 
else query += ",true AS is_key\n";
```
![Error](https://user-images.githubusercontent.com/104570390/165754171-7e613222-64b4-4470-8217-8817556a7f4e.png)

**Comment by levinsv** [comment]
fix in commit 42db7dbb . But testing was not carried out, there is no version 10.
