### ISSUE TITLE
Прошу увеличить ширину колонки Size в статистике таблиц

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#26]
Добрый дкнь,
Сейчас ширина колонки `Size` по умолчанию для окна статистики таблиц слишком мала и её приходится постоянно расширять руками, что немного напрягает...
![изображение](https://user-images.githubusercontent.com/10084993/167778567-6fdd67da-b877-46a2-b8cb-e0d99d937b87.png)
прошу сделать шире изначально...
![изображение](https://user-images.githubusercontent.com/10084993/167779066-8e735f28-5c2e-4e69-8c77-089542c13eef.png)

**Comment by levinsv** [comment]
Исправление в этом коммите https://github.com/levinsv/pgadmin3/commit/8a806cea86d030fa54b443caf4eeef34f63678cf

**Comment by sgrinko** [comment]
Спасибо!
