### ISSUE TITLE
Функционал для шифрования файла с паролями pgpass.conf

### ISSUE THREAD

**Issue by xinferum** [levinsv/pgadmin3#27]
Добрый день.

Спасибо большое за поддержку PgAdmin3.

У меня вопрос, нет ли возможности реализовать шифрование файла хранилища паролей? В данный момент файл pgpass.conf хранит данные для подключения в открытом виде, примерно по такому пути:
```
c:\users\%username%\appdata\roaming\postgresql\pgpass.conf
```
Было бы полезно иметь возможность зашифровать pgpass.conf мастер паролем и указывать его при запуске программы.

**Comment by levinsv** [comment]
pgAdmin3 linux ориентированный клиент. А там доступ к файлу регулируется назначением владельца файла.
Сделайте владельцем pgpass.conf только себя и уберите все прочие разрешения у других учётных записей. И тогда только вы сможете его открывать.
