### ISSUE TITLE
Ошибка скриптования объекта Event Trigger

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#30]
Добрый день,

Во-первых, спасибо большое за продолжение работ по поддержке программы!

Суть проблемы:
при создании триггеров событий такими командами как:
`CREATE EVENT TRIGGER dbots_tg_on_ddl_event ON DDL_COMMAND_END  EXECUTE PROCEDURE public.dbots_on_ddl_event();`
`CREATE EVENT TRIGGER dbots_tg_on_drop_event ON SQL_DROP  EXECUTE PROCEDURE public.dbots_on_drop_event();`
и последующим их скриптованием, получаем вот такое:
```
-- Event Trigger: dbots_tg_on_ddl_event on database scan

-- DROP EVENT TRIGGER dbots_tg_on_ddl_event;

CREATE EVENT TRIGGER dbots_tg_on_ddl_event ON ddl command end EXECUTE PROCEDURE public.dbots_on_ddl_event();
```
и
```
-- Event Trigger: dbots_tg_on_drop_event on database scan

-- DROP EVENT TRIGGER dbots_tg_on_drop_event;

CREATE EVENT TRIGGER dbots_tg_on_drop_event ON sql drop EXECUTE PROCEDURE public.dbots_on_drop_event();
```
Прошу обратить внимание, что пропал знак подчеркивания внутри имени события на которую подписывается триггер:
`DDL_COMMAND_END` -> `ddl command end`
`SQL_DROP` -> `sql drop`

Прошу поправить скриптование таких объектов.

Спасибо!

**Comment by levinsv** [comment]
Исправлено в commit https://github.com/levinsv/pgadmin3/commit/cb11507b4fa2ed3f6889261d69f15edf529990d6
