### ISSUE TITLE
Поддержка 15-й версии ?

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#31]
Добрый день,

Планируется ли встраивание поддержки 15-й версии?

Спасибо!

**Comment by levinsv** [comment]
Я добавил частичную поддержку 15 версии.
Может потом ещё что нибудь доработаю, если необходимость появиться.

**Comment by sgrinko** [comment]
Спасибо большое, смотрим :)

**Comment by sgrinko** [comment]
И ещё одна просьба...
Можно ли вот здесь начать указывать какую-либо информацию об очередной версии (в любом виде)
![изображение](https://user-images.githubusercontent.com/10084993/202469696-a1e5e022-a89c-4270-a1a7-1bcaeeb70818.png)
Без этого порой сложно понять, какую версию сейчас используем....

**Comment by levinsv** [comment]
Тут [df636ac](https://github.com/levinsv/pgadmin3/commit/df636ac670f789d3c19193cb3a2729eedc8930d1) убрано предупреждение.
Информацию о версии можно брать из даты компиляции (в данном случае 9 ноября 2022).
Все существенные изменения изменяют эту дату.

**Comment by sgrinko** [comment]
Спасибо!
