### ISSUE TITLE
Изменение языка программы

### ISSUE THREAD

**Issue by sgrinko** [levinsv/pgadmin3#35]
Добрый день,

Во-первых, спасибо большое за поддержку программы!

Ранее при использовании программы у меня не было никаких проблем с переключением языка интерфейса на английский язык.
Однако в текущей версии появилась проблема. У меня OS русскоязычная и поэтому программа всегда пыталась перейти на использование русского языка. Я менял его в настройках. Однако сейчас появилась проблема:
![изображение](https://github.com/levinsv/pgadmin3/assets/10084993/15ab300c-f3a8-4ab0-90d9-901ee7a9d49b)
нет возможности выбрать другой язык, так как нет ни одного языка для выбора.
Подкаталог `i18n` у меня есть и в нем много языков:
```
04.04.2022  17:05    <DIR>          .
04.04.2022  17:05    <DIR>          ..
04.04.2022  17:05    <DIR>          ca_ES
04.04.2022  17:05    <DIR>          cs_CZ
04.04.2022  17:05    <DIR>          de_DE
04.04.2022  17:05    <DIR>          es_ES
04.04.2022  17:05    <DIR>          fr_FR
04.04.2022  17:05    <DIR>          ja_JP
04.04.2022  17:05    <DIR>          lv_LV
04.04.2022  17:05    <DIR>          pl_PL
04.04.2022  17:05    <DIR>          ru_RU
04.04.2022  17:05    <DIR>          sr_RS
04.04.2022  17:05    <DIR>          zh_CN
14.02.2018  19:45             1 748 pgadmin3.lng
14.02.2018  19:45            36 169 pg_settings.csv
```
Ранее возможность выбора языка была, а сейчас его нет.
Подскажите как можно установить английский язык?

Проблема в использовании к примеру русского в том, что выскакивает вот такая проблема:
![изображение](https://github.com/levinsv/pgadmin3/assets/10084993/6da5fb9b-3796-486c-9974-24a458f54b1a)
но я бы конечно всё равно хотел бы изменить язык на английский, привык уже

**Comment by levinsv** [comment]
Добрый день!
В 3.1.6 поменялось немного в определении локалей, а English (U.S.) был переименован в English (United States).
Исправить не  сложно.

**Comment by sgrinko** [comment]
Спасибо большое!
Заработало!

**Comment by levinsv** [comment]
Тогда закрываю.
