### ISSUE TITLE
pgAdmin Server Status Icon Issue

### ISSUE THREAD

**Issue by winmedatgmaildotcom** [levinsv/pgadmin3#36]
Thank you very much for keeping pgAdmin 3 updated with the latest PostgreSQL versions.
I have encountered an issue with the Server Status and was hoping for some assistance. As seen in the attached screenshot, the “Cancel Query” and “Terminate backend” icon buttons do not seem to be functioning properly. Whenever I click on a target session, it briefly flashes but then becomes disabled and inactive. I am unsure if this is a bug or if there is a workaround that I could try.
![pgadmin-server-status](https://github.com/levinsv/pgadmin3/assets/102481118/bd4f3fa2-a1ea-4f99-8a74-7a4be8fb1548)

**Comment by levinsv** [comment]
You need to shift the focus to the "Activity" window. To do this, click on the title of the "Activity" window.

**Comment by winmedatgmaildotcom** [comment]
Thank you for the guidence. It worked but now only 'Cancel Query' is enabled. The 'Terminate backend' button is still disabled. Am I missing something again?


![server-status2](https://github.com/levinsv/pgadmin3/assets/102481118/7835cde7-eb6b-46b0-aeb7-7406746b9a47)

**Comment by winmedatgmaildotcom** [comment]
Thank you for the guidence. It worked but now only 'Cancel Query' is enabled. The 'Terminate backend' button is still disabled. Am I missing something again?

![server-status2](https://github.com/levinsv/pgadmin3/assets/102481118/d672b954-3621-46c4-b181-ca85ce815e7f)

**Comment by levinsv** [comment]
pgAdmin3 did not find the pg_terminate_backend (pid integer) function on your server.

`SELECT proname, pronargs, proargtypes[0] AS arg0, proargtypes[1] AS arg1, proargtypes[2] AS arg2
  FROM pg_proc
  JOIN pg_namespace n ON n.oid=pronamespace
 WHERE proname IN ('pg_tablespace_size', 'pg_file_read', 'pg_logfile_rotate',
                  'pg_postmaster_starttime', 'pg_terminate_backend', 'pg_reload_conf',
                  'pgstattuple', 'pgstatindex','bt_index_parent_check')
   AND nspname IN ('pg_catalog', 'public')
`

**Comment by winmedatgmaildotcom** [comment]
Found out the terminate backend works on PostgreSQL 13 but not on version 15. Here is the query result on both servers.

The query result in version 13.
![v13](https://github.com/levinsv/pgadmin3/assets/102481118/3db7f443-4f26-49e1-bd05-efdf7f6a8149)


The query result in version 15.
![v15](https://github.com/levinsv/pgadmin3/assets/102481118/e566a430-c7e7-446c-b769-9d58ba4b50eb)

**Comment by winmedatgmaildotcom** [comment]
Perfect! The issue is resolved after the fix.
Thank you!
