### ISSUE TITLE
Вопросы по использованию

### ISSUE THREAD

**Issue by tracktor-git** [levinsv/pgadmin3#38]
Привет!

Как отключить автосохранение последнего выполненого запроса в редакторе запросов?
И как отключить иконки, которые прявляются слева по наведению на левую часть в браузере объектов?

**Comment by levinsv** [comment]
Привет!

Эти возможности не отключаются. Но добавить возможность настройки не сложно.

**Comment by tracktor-git** [comment]
Добавь тогда, пожалуйста.
