### ISSUE TITLE
postgresql 17

### ISSUE THREAD

**Issue by walery92** [levinsv/pgadmin3#49]
Добавьте плиз subj, а то ругается на окно состояние сервера при включенной репликации - Column not found in pgSet: av_replica

**Comment by levinsv** [comment]
Такое возможно только для 10,11,12 версии сервера.
Я поправил этот момент.

**Comment by walery92** [comment]
Теперь другие полезли
![image](https://github.com/user-attachments/assets/e1558deb-cd0b-4b60-ac57-f659bd8a83f5)
![image](https://github.com/user-attachments/assets/160a61ab-43c0-40f5-bbac-5d5832c80e89)

**Comment by walery92** [comment]
Да, немного ошибся - переползаю с 12-го на 17-й, на 12 если есть публикации - такие сообщения
И еще вопрос - если я подкину pg_dump, pg_restore и pqsql от 17го - нормально будет?

**Comment by levinsv** [comment]
Поправил.
