### ISSUE TITLE
Can't Open/Connect to Newly Created Postgres 10 database

### ISSUE THREAD

**Issue by bradleyf** [levinsv/pgadmin3#5]
I can use the latest pgadmin3 build to create a new database on postgres 10, but when I try to open/connect to it, I am getting an error dialog box which says "ERROR: No such Database: <database_name>".   The database does appear in the object browser tree, each time I connect to the server.   It a;los does show the properties of the database in the properties tab, and the SQL for the database created in the SQL pane, after I click ok on the error dialog.   It just won't open/connect to that database.   It will connect to prior existing databases on the same server.      

I hope you can fix this issue as I think your enhanced version of pgadmin 3 is my favorite postgresql tool (over the latest pgadmin 4).

**Comment by levinsv** [comment]
This message says that a non-existing database is specified (server properties..).
In the "Maintenance DB" specify the correct name or postgres or template1.
Look at the psql -l command which databases exist on the server.

**Comment by bradleyf** [comment]
No, not the case.   The database opens/connects fine in pgadmin 4

**Comment by bradleyf** [comment]
I took a look again.  It's my mistake.  It was trying to connect via pgbouncer and the new db was not set up in pgbouncer yet.   Sorry for the false alarm.   I'm closing this issue.
