### ISSUE TITLE
Search Objects bug

### ISSUE THREAD

**Issue by EDIsaev** [levinsv/pgadmin3#9]
Добрый день!
К сожалению не нашёл как с Вами можно связаться, потому напишу тут
При поиске объекта (Ctrl+G) при нажатии кнопи поиск вылетает исключение

```
[Window Title]
pgAdmin III
[Main Instruction]
An error has occurred:
[Content]
12:22:50: Error: ERROR:  column p.prokind does not exist
LINE 1: ...'trigger' THEN 'Trigger Functions' ELSE case when p.prokind=...
                                                             ^
HINT:  Perhaps you meant to reference the column "p.probin".
[OK]
```
![search_object](https://user-images.githubusercontent.com/11036770/90388525-3229dd80-e088-11ea-9390-8573a8c48624.png)

не могли бы Вы это пофиксить?
Или дать наводку с чем это может быть связано, если это проблема локального характера

**Comment by levinsv** [comment]
Что такое я уже исправлял. На версиях PG от 10 должно нормально работать. У вас последний exe-шник скачан.

**Comment by EDIsaev** [comment]
exe-шник на момент публикации был последний да, но версия у нас не 10, а 9.6.13

**Comment by levinsv** [comment]
Версия 9.6 не поддерживается.
